### ISSUE TITLE
定理环境中无法同时展示两张交换图

### ISSUE THREAD

**Issue by shadowash0215** [FrightenedFoxCN/mkdocs-mathenv-plugin#1]
本人 mkdocs 版本 1.4.2，python 版本 3.9.13，在写作如下内容时第二张交换图无法在网页显示：

!!! info "定义"
    环 $R$ 上的模 $P$ 被称为**投射模**(projective module)，是指任意给下面一个 $R$-模同态图表  

    \tikzcd
        & P \arrow[d, "f"] & \\
        A \arrow[r, "g"] & B \arrow[r] & 0

    并且底行都是正合的，也就是说 $g$ 是满射，都存在 $R$-模同态 $h: P \rightarrow A$ 使得 $g \circ h = f$.

    这个定义就是在说存在 $h$ 使得下面的图表交换。

    \tikzcd
        & P \arrow[ld, swap, "h"] \arrow[d, "f"] & \\
        A \arrow[r, "g"] & B \arrow[r] & 0
        
<img width="572" alt="issue" src="https://github.com/FrightenedFoxCN/mkdocs-mathenv-plugin/assets/122452199/33089dd3-23fd-487b-9d01-ba26588672c5">

mkdocs.yml 中关于 tikzcd 的配置均已正确开启。

**Comment by FrightenedFoxCN** [comment]
在最新的 commit 中已经完成修复。
